# @format

version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # RabbitMQ Management Console port
    environment:
      RABBITMQ_DEFAULT_USER: user # Default username
      RABBITMQ_DEFAULT_PASS: password # Default password

volumes:
  redis_data:
