apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image }}
          ports:
            - containerPort: {{ .Values.fastapi.service.port }}
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.servicePort }}"
            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.rabbitmq.username }}:{{ .Values.rabbitmq.password }}@rabbitmq:{{ .Values.rabbitmq.servicePorts.amqp }}/"
