apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.servicePorts.amqp }}
    - name: management
      port: {{ .Values.rabbitmq.servicePorts.management }}
