apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: mybrac-stg
  labels:
    app: rabbitmq-svc
spec:
  type: ClusterIP
  ports:
    - name: rabbitmq
      port: 5672
    - name: management
      port: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: mybrac-stg
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-test
          image: rabbitmq:management-alpine
          ports:
            - name: rabbitmq
              containerPort: 5672
            - name: management 
              containerPort: 15672 
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: ""
            - name: RABBITMQ_DEFAULT_PASS
              value: ""
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {} 

